import {NextResponse} from "next/server";import {demoPlan,openRouterJSON} from "../../../lib/eazy-ai";import {PRICE_CATALOG_TEXT,ABIDJAN_PRICE_CATALOG} from "../../lib/price-catalog";
export const runtime="nodejs";
export async function POST(req:Request){try{const input=await req.json();const system=`Tu es le moteur de planification Eazy 1000 pour l'Afrique francophone. Retourne UNIQUEMENT un JSON avec summary, meals et shopping. Respecte strictement budget, personnes, jours, garde-manger, préférences, start_date, meal_slots, cuisines_included et cuisines_excluded. cuisines_included contient les familles culinaires autorisées. cuisines_excluded contient les familles explicitement décochées par l'utilisateur : n'en propose AUCUN plat, aucune variante ni recommandation. Si une cuisine est exclue, traite cette exclusion comme une contrainte stricte supérieure à la variété du planning. start_date est la première date du calendrier. Génère EXACTEMENT un repas pour chaque meal_slot sélectionné pour chaque jour demandé, sans créneau supplémentaire. Chaque meal doit contenir date au format YYYY-MM-DD, day (1..N) et meal qui reprend exactement le libellé du créneau demandé. Les dates doivent être successives à partir de start_date. Répartis les recommandations uniquement entre les cuisines présentes dans cuisines_included, avec de la variété entre elles quand plusieurs sont autorisées. Ne crée pas d'associations culinaires fantaisistes. MODE RAPIDE: ce premier appel doit rester compact afin d’afficher le calendrier le plus vite possible. Pour chaque meal retourne UNIQUEMENT title, day, date, meal, estimated_cost, match, reason, cuisine et ingredients. NE GÉNÈRE PAS les étapes de cuisine ici et n’ajoute pas de champ steps. ingredients est une liste de {name,quantity,unit,estimated_price,pantry_match} et doit permettre de construire une vraie liste de courses. pantry_match=true seulement si le garde-manger fourni couvre raisonnablement cet ingrédient. shopping doit agréger UNIQUEMENT les ingrédients manquants sur tout le plan sous {name,quantity,unit,estimated_price,for_meals}. Pour diabète, hypertension, colopathie ou autre maladie: reste prudent, n'annonce jamais traiter une maladie et ajoute notice. RÈGLE PRIX CRITIQUE: ne fabrique JAMAIS un prix. Utilise en priorité le catalogue vérifié fourni ci-dessous. Pour un produit emballé, estimated_price doit être le PRIX DU CONDITIONNEMENT ENTIER réellement acheté, jamais le prorata de la quantité consommée. shopping doit ajouter product_name, package_quantity, package_unit, units_to_buy, checkout_price, quantity_used, leftover_quantity, leftover_unit, price_source, price_observed_at. Pour le vivrier vendu au poids, tu peux calculer checkout_price à partir du prix/kg vérifié et d'une quantité d'achat réaliste. Si aucun produit du catalogue ne correspond de façon raisonnable, mets estimated_price et checkout_price à null et price_source="non vérifié" au lieu d'inventer. summary.estimated_total doit être la somme des checkout_price réellement déboursés, pas la valeur proratisée consommée. Les reliquats sont destinés au garde-manger. CATALOGUE PRIX ABIDJAN VÉRIFIÉ:\n${PRICE_CATALOG_TEXT}`;
 if(!process.env.OPENROUTER_API_KEY)return NextResponse.json({error:"provider_not_configured",message:"OPENROUTER_API_KEY absente de l’environnement Production Vercel."},{status:503}); const ai=await openRouterJSON(system+"\nCONTRAINTE BUDGET ABSOLUE: le total caisse de shopping doit être inférieur ou égal au budget utilisateur. Si le catalogue implique un dépassement, choisis des repas moins chers et réutilise les mêmes conditionnements entre plusieurs repas.",input);if(!ai)return NextResponse.json({error:"provider_empty",message:"OpenRouter n’a retourné aucun résultat."},{status:502});const norm=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const toBase=(q:number,u:string)=>u==="kg"?q*1000:u==="l"?q*1000:u==="cl"?q*10:q;
const dimension=(u:string)=>["g","kg"].includes(u)?"mass":["ml","cl","l"].includes(u)?"volume":["unit","unite","unité","boule","piece","pièce"].includes(u)?"unit":"other";
const specificity=(name:string,alias:string)=>{const n=norm(alias);if(name===n)return 1000+n.length;if(name.includes(n))return 500+n.length;if(n.includes(name))return 100+n.length;return -1};
const priced=(ai.shopping||[]).map((item:any)=>{
 const name=norm(String(item.name||"")),q=Number(item.quantity)||0,u=norm(String(item.unit||""));
 const candidates=ABIDJAN_PRICE_CATALOG.map(r=>({r,score:Math.max(...r.aliases.map(a=>specificity(name,a)))})).filter(x=>x.score>=0).sort((x,y)=>y.score-x.score);
 const dim=dimension(u);
 const compatible=candidates.filter(({r})=>dimension(norm(r.packageUnit))===dim);
 if(!compatible.length)return {...item,estimated_price:null,checkout_price:null,price_source:"non vérifié"};
 const need=toBase(q,u);
 const evaluated=compatible.map(({r,score})=>{const pu=norm(r.packageUnit),pack=toBase(Number(r.packageQty),pu);if(r.kind==="market"){const checkout=Math.ceil((r.price*(need/pack))/5)*5;return {r,score,units:1,checkout,pack,left:0}}const units=Math.max(1,Math.ceil(need/pack));return {r,score,units,checkout:r.price*units,pack,left:Math.max(0,pack*units-need)}}).sort((x,y)=>y.score-x.score||x.checkout-y.checkout);
 const best=evaluated[0],ref=best.r;
 return {...item,product_name:ref.product,package_quantity:ref.kind==="market"?item.quantity:ref.packageQty,package_unit:ref.kind==="market"?item.unit:ref.packageUnit,units_to_buy:best.units,checkout_price:best.checkout,estimated_price:best.checkout,quantity_used:item.quantity,leftover_quantity:best.left,leftover_unit:dim==="mass"?"g":dim==="volume"?"ml":item.unit,price_source:ref.source,price_observed_at:ref.observedAt}
});ai.shopping=priced;const shoppingByName=new Map(priced.map((x:any)=>[norm(String(x.name||"")),x]));ai.meals=(ai.meals||[]).map((meal:any)=>({...meal,ingredients:(meal.ingredients||[]).map((ingredient:any)=>{const key=norm(String(ingredient.name||""));const shop:any=shoppingByName.get(key)||priced.find((x:any)=>{const n=norm(String(x.name||""));return key===n||key.includes(n)||n.includes(key)});return shop?{...ingredient,estimated_price:shop.checkout_price,checkout_price:shop.checkout_price,product_name:shop.product_name,package_quantity:shop.package_quantity,package_unit:shop.package_unit,units_to_buy:shop.units_to_buy,price_source:shop.price_source,price_observed_at:shop.price_observed_at}:ingredient})}));ai.summary={...(ai.summary||{}),estimated_total:priced.reduce((n:number,x:any)=>n+(x.checkout_price||0),0)};console.log("[meal-plan] pricing",{shopping:priced.map((x:any)=>({name:x.name,quantity:x.quantity,unit:x.unit,llm_estimated_price:x.estimated_price,checkout_price:x.checkout_price,product_name:x.product_name,package_quantity:x.package_quantity,package_unit:x.package_unit,units_to_buy:x.units_to_buy,price_source:x.price_source})),estimated_total:ai.summary.estimated_total});return NextResponse.json(ai);}catch(e:any){return NextResponse.json({error:"plan_failed",message:e.message},{status:502})}}
