"use client";
import {useEffect,useRef,useState} from "react";
import {recipes,Recipe,Ingredient} from "./data";
import {EazyAPI} from "../lib/api-client";
import {Home,Sparkles,ShoppingBasket,UserRound,Camera,WalletCards,Target,Video,Search,ArrowRight,X,Check,Clock3,ChevronLeft,RefreshCw,ChefHat,Play,Plus,PackageOpen,CalendarDays} from "lucide-react";

type Pantry={name:string;quantity:number|null;unit:string;confidence:number};
type PlanIngredient={name:string;quantity?:number|string|null;unit?:string;estimated_price?:number;pantry_match?:boolean};\ntype Meal={title:string;day:number;date?:string;meal:string;estimated_cost:number;match:number;reason?:string;ingredients?:PlanIngredient[]};
type PlanResult={mode?:string;summary:any;meals:Meal[];shopping:any[];notice?:string};
type Cart=Ingredient&{id:string;recipe:string;done:boolean};
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(n||0)+" F";

export default function Page(){
 const [tab,setTab]=useState("home"),[budget,setBudget]=useState(15000),[people,setPeople]=useState(2),[days,setDays]=useState(4),[goal,setGoal]=useState("Manger mieux"),[planner,setPlanner]=useState(false),[busy,setBusy]=useState(""),[toast,setToast]=useState(""),[pantry,setPantry]=useState<Pantry[]>([]),[plan,setPlan]=useState<PlanResult|null>(null),[video,setVideo]=useState<any>(null),[selected,setSelected]=useState<Recipe|null>(null),[cart,setCart]=useState<Cart[]>([]),[planMeal,setPlanMeal]=useState<Meal|null>(null),[delivery,setDelivery]=useState<any>(null),[mealSlots,setMealSlots]=useState<string[]>(["Déjeuner","Dîner"]),[videoInput,setVideoInput]=useState("");
 const scanRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{setPantry(JSON.parse(localStorage.getItem("eazy1000-pantry")||"[]"));setPlan(JSON.parse(localStorage.getItem("eazy1000-plan")||"null"));setVideo(JSON.parse(localStorage.getItem("eazy1000-video-result")||"null"));setCart(JSON.parse(localStorage.getItem("eazy1000-cart")||"[]"))}catch{}},[]);
 const flash=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 const scan=async(fs:FileList|null)=>{if(!fs?.length)return;setBusy("Eazy analyse tes aliments");try{const imgs=await Promise.all(Array.from(fs).slice(0,6).map(f=>new Promise<string>((ok,ko)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=()=>ko(r.error);r.readAsDataURL(f)})));const out:any=await EazyAPI.scanPantry(imgs);setPantry(out.items||[]);localStorage.setItem("eazy1000-pantry",JSON.stringify(out.items||[]));flash((out.items?.length||0)+" aliments ajoutés au garde-manger")}catch(e:any){flash("Analyse impossible : "+e.message)}finally{setBusy("")}};
 const generate=async()=>{if(!mealSlots.length){flash("Choisis au moins un repas");return}setBusy("Eazy construit ton calendrier");try{const start_date=new Date().toISOString().slice(0,10);const out:any=await EazyAPI.createMealPlan({budget,people,days,goal,pantry,start_date,meal_slots:mealSlots});setPlan(out);localStorage.setItem("eazy1000-plan",JSON.stringify(out));setPlanner(false);setTab("plan");flash("Plan généré avec succès")}catch(e:any){flash("Plan impossible : "+e.message)}finally{setBusy("")}};
 const analyzeVideo=async(urlArg?:string)=>{const url=(urlArg||videoInput).trim();if(!url){flash("Colle un lien vidéo à analyser");return;}setBusy("Eazy comprend la vidéo");try{let out:any=await EazyAPI.videoRecipe(url);if(out.status==="queued"&&out.requestId){for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,2000));out=await EazyAPI.videoStatus(out.requestId);if(out.status!=="IN_QUEUE"&&out.status!=="IN_PROGRESS")break}}setVideo(out);localStorage.setItem("eazy1000-video-result",JSON.stringify(out));setTab("video");flash("Analyse vidéo terminée")}catch(e:any){flash("Vidéo : "+e.message)}finally{setBusy("")}};
 const addRecipe=(r:Recipe)=>{const next=[...cart,...r.ingredients.filter(i=>!cart.some(c=>c.id===r.id+"-"+i.name)).map(i=>({...i,id:r.id+"-"+i.name,recipe:r.name,done:false}))];setCart(next);localStorage.setItem("eazy1000-cart",JSON.stringify(next));flash("Ajouté aux courses")};
 return <main>{toast&&<div className="toast">{toast}</div>}{busy&&<div className="working"><div className="pulse"><Sparkles/></div><b>{busy}</b><span>Analyse en cours…</span></div>}
 <header><div className="brand">Eazy <b>1000</b></div><span className="apiDot">LIVE</span></header>
 <section className="screen">
 {tab==="home"&&<><div className="hello"><p>Bonsoir,</p><h1>On mange bien<br/>ce soir.</h1></div><div className="search"><Search/><span>Une envie ? Un ingrédient ? Une vidéo ?</span></div>
 <div className="contextGrid"><button onClick={()=>scanRef.current?.click()}><Icon I={Camera}/><b>Scanner<br/>mes aliments</b></button><button onClick={()=>setPlanner(true)}><Icon I={WalletCards}/><b>Mon<br/>budget</b></button><button onClick={()=>setPlanner(true)}><Icon I={Target}/><b>Mon<br/>objectif</b></button><button onClick={()=>document.getElementById("video-link")?.scrollIntoView({behavior:"smooth"})}><Icon I={Video}/><b>Une<br/>vidéo</b></button></div><input hidden ref={scanRef} multiple type="file" accept="image/*" onChange={e=>scan(e.target.files)}/>
 <div id="video-link" className="videoTester"><div><small>RECETTE DEPUIS UNE VIDÉO</small><h3>Colle un lien TikTok, Instagram, YouTube ou une URL vidéo publique.</h3></div><div className="videoInput"><input value={videoInput} onChange={e=>setVideoInput(e.target.value)} placeholder="https://…" inputMode="url"/><button onClick={()=>analyzeVideo(videoInput)}><ArrowRight/></button></div><p>Le lien est envoyé au pipeline vidéo configuré. Le résultat apparaît dans l’écran Recette extraite.</p></div>{pantry.length>0&&<button className="statusCard" onClick={()=>setTab("pantry")}><div><small>GARDE-MANGER ACTIF</small><b>{pantry.length} aliments reconnus</b><span>Voir et vérifier les produits</span></div><ArrowRight/></button>}
 {plan&&<button className="planHero" onClick={()=>setTab("plan")}><small>TON DERNIER PLAN</small><h2>{plan.meals?.length||0} repas · {money(plan.summary?.estimated_total)}</h2><p>{plan.summary?.saved_by_pantry?money(plan.summary.saved_by_pantry)+" économisés grâce à ce que tu as déjà":goal}</p><ArrowRight/></button>}
 <div className="sectionTitle"><div><small>INSPIRATION</small><h2>Tu peux presque les cuisiner</h2></div></div><div className="cards">{recipes.slice(0,4).map(r=><RecipeCard key={r.id} r={r} open={()=>setSelected(r)}/>)}</div></>}
 {tab==="plan"&&<PlanView plan={plan} regenerate={()=>setPlanner(true)} openMeal={setPlanMeal} addAll={()=>{const items=(plan?.shopping||[]).map((x:any,i:number)=>({name:x.name,qty:String(x.quantity||"à prévoir")+" "+(x.unit||""),price:x.estimated_price||0,id:"plan-"+i+"-"+x.name,recipe:"Plan Eazy",done:false}));const next=[...cart,...items.filter((x:any)=>!cart.some(c=>c.id===x.id))];setCart(next);localStorage.setItem("eazy1000-cart",JSON.stringify(next));setTab("cart");flash("Liste du plan ajoutée")}} deliver={()=>setDelivery({title:"Courses du plan Eazy",items:plan?.shopping||[]})}/>}
 {tab==="pantry"&&<PantryView items={pantry} rescan={()=>scanRef.current?.click()}/>}
 {tab==="video"&&<VideoView data={video}/>}
 {tab==="cart"&&<CartView cart={cart} setCart={(x:Cart[])=>{setCart(x);localStorage.setItem("eazy1000-cart",JSON.stringify(x))}}/>}
 </section>
 <nav>{[["home",Home,"Aujourd’hui"],["plan",Sparkles,"Mes repas"],["cart",ShoppingBasket,"Courses"],["pantry",PackageOpen,"Garde-manger"]].map(([id,I,l]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><I/><span>{l}</span></button>)}</nav>
 {planner&&<Planner budget={budget} setBudget={setBudget} people={people} setPeople={setPeople} days={days} setDays={setDays} goal={goal} setGoal={setGoal} mealSlots={mealSlots} setMealSlots={setMealSlots} close={()=>setPlanner(false)} run={generate}/>}
 {selected&&<RecipeModal r={selected} close={()=>setSelected(null)} add={()=>addRecipe(selected)}/>}\n {planMeal&&<PlanMealModal meal={planMeal} close={()=>setPlanMeal(null)} add={()=>{const items=(planMeal.ingredients||[]).filter(x=>!x.pantry_match).map((x,i)=>({name:x.name,qty:String(x.quantity||"à prévoir")+" "+(x.unit||""),price:x.estimated_price||0,id:"meal-"+planMeal.title+"-"+i,recipe:planMeal.title,done:false}));const next=[...cart,...items.filter(x=>!cart.some(c=>c.id===x.id))];setCart(next);localStorage.setItem("eazy1000-cart",JSON.stringify(next));setPlanMeal(null);setTab("cart");flash("Ingrédients manquants ajoutés")}} deliver={()=>{setDelivery({title:planMeal.title,items:(planMeal.ingredients||[]).filter(x=>!x.pantry_match)});setPlanMeal(null)}}/>}\n {delivery&&<DeliverySheet order={delivery} close={()=>setDelivery(null)} confirm={(store:string)=>{flash("Panier préparé chez "+store);setDelivery(null)}}/>}
 </main>
}
function Icon({I}:{I:any}){return <span className="glyph"><I/></span>}
function Planner({budget,setBudget,people,setPeople,days,setDays,goal,setGoal,mealSlots,setMealSlots,close,run}:any){const goals=["Manger mieux","Petit budget","Perdre du poids","Faire avec ce que j’ai","Me régaler"],slots=["Petit-déjeuner","Déjeuner","Dîner","Goûter","Collation"];const toggle=(x:string)=>setMealSlots((v:string[])=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);return <div className="overlay top"><div className="sheet plan"><button className="close" onClick={close}><X/></button><p className="eyebrow">CRÉER MON PLAN</p><h1>Quel est le plan ?</h1><p className="muted">Choisis les moments que tu veux planifier. Eazy les répétera chaque jour sur la durée choisie.</p><div className="mealSlotGrid">{slots.map(x=><button key={x} className={mealSlots.includes(x)?"selectedSlot":""} onClick={()=>toggle(x)}><span>{mealSlots.includes(x)?<Check/>:<Plus/>}</span><b>{x}</b><small>{x==="Goûter"||x==="Collation"?"Optionnel":"Repas"}</small></button>)}</div><div className="goalRow">{goals.map(g=><button key={g} className={goal===g?"chosen":""} onClick={()=>setGoal(g)}>{g}</button>)}</div><div className="budgetBox"><small>MON BUDGET</small><b>{money(budget)}</b><input type="range" min="2000" max="100000" step="500" value={budget} onChange={e=>setBudget(Number(e.target.value))}/><div><span>2 000 F</span><span>100 000 F</span></div></div><div className="counters"><Counter label="Personnes" value={people} set={setPeople} min={1} max={12}/><Counter label="Jours" value={days} set={setDays} min={1} max={14}/></div><div className="calendarPreview"><CalendarDays/><div><small>CALENDRIER</small><b>{days} jour{days>1?"s":""} · {mealSlots.length} créneau{mealSlots.length>1?"x":""}/jour</b><span>{days*mealSlots.length} propositions seront générées à partir d’aujourd’hui</span></div></div><button className="cta" onClick={run}>Générer mon calendrier <Sparkles/></button></div></div>}
function Counter({label,value,set,min,max}:any){return <div><small>{label}</small><section><button onClick={()=>set(Math.max(min,value-1))}>−</button><b>{value}</b><button onClick={()=>set(Math.min(max,value+1))}>+</button></section></div>}
function PlanView({plan,regenerate,openMeal,addAll,deliver}:{plan:PlanResult|null;regenerate:any;openMeal:any;addAll:any;deliver:any}){if(!plan)return <Empty title="Aucun plan pour le moment." action="Créer mon plan" go={regenerate}/>;const groups=plan.meals.reduce((a:any,m:Meal)=>{const k=m.date||String(m.day);(a[k]??=[]).push(m);return a},{});const label=(d:string,ms:Meal[])=>{if(!ms[0]?.date)return "Jour "+ms[0]?.day;const dt=new Date(ms[0].date+"T12:00:00");return new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long"}).format(dt)};return <><div className="hello compact"><p>TON CALENDRIER EAZY</p><h1>{plan.meals.length} moments à savourer.</h1></div><div className="resultSummary"><div><small>BUDGET</small><b>{money(plan.summary?.budget)}</b></div><div><small>ESTIMATION</small><b>{money(plan.summary?.estimated_total)}</b></div><div><small>ÉCONOMISÉ</small><b>{money(plan.summary?.saved_by_pantry)}</b></div></div><div className="dayGroups">{Object.entries(groups).map(([date,meals]:any)=><section key={date}><div className="dayHead"><span>{String(meals[0].day).padStart(2,"0")}</span><div><small>JOUR {meals[0].day}</small><h2>{label(date,meals)}</h2></div></div><div className="mealResults">{meals.map((m:Meal,i:number)=><article key={i} onClick={()=>openMeal(m)}><span>{m.meal.slice(0,2).toUpperCase()}</span><div><small>{m.meal}</small><h3>{m.title}</h3><p>{m.reason||"Voir ingrédients, courses et livraison."}</p></div><b>{m.match||90}<small>match</small></b></article>)}</div></section>)}</div><div className="planActions"><button onClick={addAll}><ShoppingBasket/> Liste de courses</button><button className="dark" onClick={deliver}><PackageOpen/> Faire livrer</button></div><button className="cook" onClick={regenerate}><RefreshCw/> Modifier mon calendrier</button>{plan.notice&&<p className="notice">{plan.notice}</p>}</>}
function PantryView({items,rescan}:{items:Pantry[];rescan:any}){return <><div className="hello compact"><p>TON CONTEXTE CUISINE</p><h1>Ton garde-manger.</h1></div><div className="pantryList">{items.map((x,i)=><article key={i}><span>{String(i+1).padStart(2,"0")}</span><div><b>{x.name}</b><small>{x.quantity==null?"Quantité à confirmer":x.quantity+" "+x.unit}</small></div><strong>{Math.round(x.confidence*100)}%</strong></article>)}</div><button className="cta" onClick={rescan}><Camera/> Ajouter des photos</button></>}
function VideoView({data}:{data:any}){if(!data)return <Empty title="Aucune vidéo analysée."/>;const rec=data.recipe||{};return <><div className="hello compact"><p>RECETTE EXTRAITE</p><h1>{rec.title||"Analyse vidéo"}</h1></div>{data.message&&<div className="statusCard"><b>{data.message}</b></div>}<h2 className="subhead">Ingrédients</h2><div className="pantryList">{(data.ingredients||[]).map((x:any,i:number)=><article key={i}><span>{String(i+1).padStart(2,"0")}</span><div><b>{x.name}</b><small>{x.quantity??"?"} {x.unit||""}</small></div></article>)}</div><h2 className="subhead">Étapes</h2><div className="steps">{(data.steps||[]).map((x:any,i:number)=><article key={i}><b>{i+1}</b><p>{x.instruction}</p>{x.video_timestamp_start!=null&&<small>{x.video_timestamp_start}s</small>}</article>)}</div></>}
function CartView({cart,setCart}:any){return <><div className="hello compact"><p>MISSION COURSES</p><h1>{cart.length?cart.filter((x:any)=>!x.done).length+" produits restants.":"Ta liste est vide."}</h1></div><div className="pantryList">{cart.map((x:any,i:number)=><article key={x.id} onClick={()=>setCart(cart.map((y:any)=>y.id===x.id?{...y,done:!y.done}:y))} className={x.done?"checked":""}><span>{x.done?<Check/>:String(i+1).padStart(2,"0")}</span><div><b>{x.name}</b><small>{x.qty} · {x.recipe}</small></div><strong>{money(x.price)}</strong></article>)}</div></>}
function RecipeCard({r,open}:{r:Recipe;open:any}){return <button className="recipeCard" onClick={open}><div className="food" style={{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(12,8,5,.72)),url("${r.image}")`}}><span className="match"><b>{r.match}</b><small>Eazy Match</small></span><div className="foodTitle"><b>{r.name}</b><small>{r.owned}% déjà chez toi</small></div></div><div className="cardText"><span><Clock3/>{r.time} min</span><strong>≈ {money(r.price)}</strong></div></button>}
function RecipeModal({r,close,add}:{r:Recipe;close:any;add:any}){return <div className="overlay"><div className="sheet"><button className="close" onClick={close}><X/></button><div className="heroFood" style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(10,7,4,.82)),url("${r.image}")`}}><div><small>{r.origin}</small><h1>{r.name}</h1></div></div><div className="recipeBody">{r.ingredients.map((i,n)=><div className="ingredient" key={i.name}><span className="ingredientMark">{String(n+1).padStart(2,"0")}</span><div><b>{i.name}</b><small>{i.qty} · {money(i.price)}</small></div></div>)}<button className="cta" onClick={add}><Plus/> Ajouter aux courses</button><button className="cook"><Play/> Commencer à cuisiner</button></div></div></div>}
function Empty({title,action,go}:{title:string;action?:string;go?:any}){return <div className="empty"><Sparkles/><h2>{title}</h2>{action&&<button className="cta" onClick={go}>{action}</button>}</div>}

function PlanMealModal({meal,close,add,deliver}:{meal:Meal;close:any;add:any;deliver:any}){const missing=(meal.ingredients||[]).filter(x=>!x.pantry_match);return <div className="overlay"><div className="sheet plan"><button className="close" onClick={close}><X/></button><p className="eyebrow">RECETTE DU PLAN</p><h1>{meal.title}</h1><p className="muted">{meal.reason}</p><div className="owned"><b>{(meal.ingredients||[]).length-missing.length}/{(meal.ingredients||[]).length} ingrédients déjà chez toi</b><small>{missing.length} à compléter</small><i style={{width:((meal.ingredients?.length||1)-missing.length)/(meal.ingredients?.length||1)*100+"%"}}/></div><div className="pantryList">{(meal.ingredients||[]).map((x,i)=><article key={i}><span>{x.pantry_match?<Check/>:String(i+1).padStart(2,"0")}</span><div><b>{x.name}</b><small>{x.quantity??"à prévoir"} {x.unit||""}</small></div><strong>{x.pantry_match?"Déjà là":money(x.estimated_price||0)}</strong></article>)}</div><div className="planActions"><button onClick={add}><ShoppingBasket/> Liste gamifiée</button><button className="dark" onClick={deliver}><PackageOpen/> Faire livrer</button></div></div></div>}
function DeliverySheet({order,close,confirm}:{order:any;close:any;confirm:any}){const [store,setStore]=useState("Allo Market");const stores=["Allo Market","Supermarché partenaire","Commerce de proximité"];const subtotal=(order.items||[]).reduce((a:number,x:any)=>a+(x.estimated_price||0),0);return <div className="overlay top"><div className="sheet delivery"><button className="close" onClick={close}><X/></button><p className="eyebrow">LIVRAISON</p><h1>Où faire les courses ?</h1><p className="muted">Choisis l’établissement qui préparera les ingrédients manquants.</p><div className="storeGrid">{stores.map(x=><button key={x} className={store===x?"selectedStore":""} onClick={()=>setStore(x)}><PackageOpen/><b>{x}</b><small>{x==="Allo Market"?"Partenaire simulé pour la démo":"Connexion à venir"}</small></button>)}</div><div className="orderBox">{(order.items||[]).map((x:any,i:number)=><div key={i}><span>{x.name}</span><b>{money(x.estimated_price||0)}</b></div>)}<div className="total"><strong>Produits estimés</strong><strong>{money(subtotal)}</strong></div><div><small>Livraison estimée</small><b>{money(1500)}</b></div><div className="total"><strong>Total indicatif</strong><strong>{money(subtotal+1500)}</strong></div></div><button className="cta" onClick={()=>confirm(store)}>Préparer chez {store} <ArrowRight/></button></div></div>}
