"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {recipes,Recipe,Ingredient} from "./data";
import {Home,Search,ShoppingBasket,UserRound,Clock3,MapPin,Truck,Plus,Check,Download,Upload,ChevronLeft,X,ScanLine,Play,ChefHat,Camera,WalletCards,Target,Video,ArrowRight,Sparkles,Flame,Leaf,UtensilsCrossed,SlidersHorizontal,PackageOpen} from "lucide-react";

type CartItem=Ingredient&{id:string;recipe:string;done:boolean};
type UserData={name:string;xp:number;streak:number;cart:CartItem[];address:string;favorites:string[]};
const initial:UserData={name:"Awa",xp:340,streak:4,cart:[],address:"Cocody, Abidjan",favorites:[]};
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(n)+" F";
const Glyph=({type}:{type:"scan"|"budget"|"goal"|"video"})=>{const I={scan:Camera,budget:WalletCards,goal:Target,video:Video}[type];return <span className={"glyph "+type}><I/></span>};

export default function Page(){
 const [tab,setTab]=useState("home"),[user,setUser]=useState<UserData>(initial),[selected,setSelected]=useState<Recipe|null>(null),[delivery,setDelivery]=useState(false),[query,setQuery]=useState(""),[toast,setToast]=useState(""),[plan,setPlan]=useState(false),fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const x=localStorage.getItem("eazy1000-user");if(x)setUser(JSON.parse(x))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("eazy1000-user",JSON.stringify(user))},[user]);
 const filtered=useMemo(()=>recipes.filter(r=>(r.name+r.origin+r.tag).toLowerCase().includes(query.toLowerCase())),[query]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1800)};
 const add=(ing:Ingredient,r:Recipe)=>{setUser(u=>({...u,xp:u.xp+5,cart:u.cart.some(c=>c.id===r.id+"-"+ing.name)?u.cart:[...u.cart,{...ing,id:r.id+"-"+ing.name,recipe:r.name,done:false}]}));flash("Ajouté à tes courses")};
 const addAll=(r:Recipe)=>{setUser(u=>({...u,xp:u.xp+20,cart:[...u.cart,...r.ingredients.filter(i=>!u.cart.some(c=>c.id===r.id+"-"+i.name)).map(i=>({...i,id:r.id+"-"+i.name,recipe:r.name,done:false}))]}));flash("Les ingrédients manquants sont prêts")};
 const exportData=()=>{const b=new Blob([JSON.stringify(user,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="eazy1000-"+Date.now()+".json";a.click();URL.revokeObjectURL(a.href)};
 const importData=(f?:File)=>{if(!f)return;const rd=new FileReader();rd.onload=()=>{try{setUser(JSON.parse(String(rd.result)));flash("Sauvegarde restaurée")}catch{flash("Fichier invalide")}};rd.readAsText(f)};
 return <main>
  {toast&&<div className="toast">{toast}</div>}
  <header><div className="brand">Eazy <b>1000</b></div><button className="avatar" onClick={()=>setTab("profile")}>{user.name[0]}</button></header>
  <section className="screen">
   {tab==="home"&&<><div className="hello"><p>Bonsoir {user.name},</p><h1>On mange bien<br/>ce soir.</h1></div>
    <div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Une envie ? Un ingrédient ? Une vidéo ?"/></div>
    <div className="contextGrid">
      <button onClick={()=>flash("Ajoute une ou plusieurs photos")}><Glyph type="scan"/><b>Scanner<br/>mes aliments</b></button>
      <button onClick={()=>setPlan(true)}><Glyph type="budget"/><b>Mon<br/>budget</b></button>
      <button onClick={()=>setPlan(true)}><Glyph type="goal"/><b>Mon<br/>objectif</b></button>
      <button onClick={()=>flash("Import vidéo bientôt disponible")}><Glyph type="video"/><b>Une<br/>vidéo</b></button>
    </div>
    <div className="sectionTitle"><div><small>PRÊT À DÉMARRER</small><h2>Tu peux presque les cuisiner</h2></div><button onClick={()=>setTab("discover")}>Tout voir</button></div>
    <div className="cards">{filtered.slice(0,4).map(r=><RecipeCard key={r.id} r={r} open={()=>setSelected(r)}/>)}</div>
    <button className="unlock" onClick={()=>setSelected(recipes[0])}><div><span className="unlockIcon"><PackageOpen/></span><small>À UN INGRÉDIENT DE DÉBLOQUER</small><h2>Un bon repas est déjà presque chez toi.</h2><p>Complète ton garde-manger et transforme ce que tu as en dîner.</p></div><ArrowRight/></button>
   </>}
   {tab==="discover"&&<><div className="hello compact"><p>INSPIRATION PERSONNALISÉE</p><h1>Voici ce que tu peux cuisiner.</h1></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Chercher une idée…"/><SlidersHorizontal/></div><div className="chips"><button className="on">Tous</button><button>Africains</button><button>Rapides</button><button>Sains</button><button>Économiques</button></div><div className="grid">{filtered.map(r=><RecipeCard key={r.id} r={r} open={()=>setSelected(r)}/>)}</div></>}
   {tab==="cart"&&<Shopping user={user} setUser={setUser} flash={flash}/>}
   {tab==="profile"&&<Profile user={user} exportData={exportData} fileRef={fileRef} importData={importData}/>}
  </section>
  <nav>{[["home",Home,"Aujourd’hui"],["discover",Sparkles,"Mes repas"],["cart",ShoppingBasket,"Cuisine"],["profile",UserRound,"Moi"]].map(([id,I,label]:any)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><I/><span>{label}</span>{id==="cart"&&user.cart.filter(x=>!x.done).length>0&&<i>{user.cart.filter(x=>!x.done).length}</i>}</button>)}</nav>
  {plan&&<Plan close={()=>setPlan(false)} done={()=>{setPlan(false);setTab("discover");flash("Ton plan de 4 jours est prêt")}}/>}
  {selected&&<RecipeSheet r={selected} close={()=>setSelected(null)} add={add} addAll={addAll} deliver={()=>setDelivery(true)}/>}
  {delivery&&selected&&<Delivery r={selected} user={user} setUser={setUser} close={()=>setDelivery(false)} flash={flash}/>}
 </main>
}
function RecipeCard({r,open}:{r:Recipe;open:()=>void}){return <button className="recipeCard" onClick={open}><div className="food" style={{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(12,8,5,.72)),url("${r.image}")`}}><span className="match"><b>{r.match}</b><small>Eazy Match</small></span>{r.local&&<i>LOCAL</i>}<div className="foodTitle"><b>{r.name}</b><small>{r.owned}% déjà chez toi</small></div></div><div className="cardText"><span><Clock3/>{r.time} min</span><strong>≈ {money(r.price)}</strong></div></button>}
function Plan({close,done}:{close:any;done:any}){return <div className="overlay top"><div className="sheet plan"><button className="close" onClick={close}><X/></button><p className="eyebrow">CRÉER MON PLAN</p><h1>Quel est le plan ?</h1><p className="muted">Choisis ce qui compte aujourd’hui. Tu peux combiner budget, objectif et ce que tu as déjà.</p><div className="missions"><button><WalletCards/><b>Finir le mois intelligemment</b><small>Faire durer mon budget</small></button><button><Leaf/><b>Manger mieux cette semaine</b><small>Des repas plus équilibrés</small></button><button><Target/><b>Perdre du poids</b><small>Adapter portions et repas</small></button><button><PackageOpen/><b>Faire avec ce que j’ai</b><small>Priorité au garde-manger</small></button><button><UtensilsCrossed/><b>Recevoir des invités</b><small>Faire plaisir sans exploser le budget</small></button><button><Sparkles/><b>Je veux juste me régaler</b><small>Priorité au goût</small></button></div><div className="budgetBox"><small>MON BUDGET</small><b>15 000 F</b><input type="range" min="2000" max="100000" defaultValue="15000"/><div><span>2 000 F</span><span>100 000 F</span></div></div><button className="cta" onClick={done}>Voir mes repas <ArrowRight/></button></div></div>}
function RecipeSheet({r,close,add,addAll,deliver}:{r:Recipe;close:any;add:any;addAll:any;deliver:any}){return <div className="overlay"><div className="sheet"><button className="close" onClick={close}><X/></button><div className="heroFood" style={{backgroundImage:`linear-gradient(180deg,transparent 45%,rgba(10,7,4,.82)),url("${r.image}")`}}><span className="heroMatch"><b>{r.match}</b><small>Eazy Match</small></span><div><small>{r.origin}</small><h1>{r.name}</h1></div></div><div className="recipeBody"><div className="meta"><span><Clock3/> {r.time} min</span><span><UserRound/> 4 personnes</span><span><ChefHat/> Facile</span></div><div className="owned"><div><b>Tu as déjà {r.owned}% des ingrédients</b><small>On complète uniquement ce qu’il te manque.</small></div><i style={{width:r.owned+"%"}}/></div><div className="ingredientHead"><h2>Ingrédients</h2><button onClick={()=>addAll(r)}>Tout ajouter</button></div>{r.ingredients.map((i,n)=><div className="ingredient" key={i.name}><span className="ingredientMark">{String(n+1).padStart(2,"0")}</span><div><b>{i.name}</b><small>{i.qty} · ≈ {money(i.price)}</small></div><button onClick={()=>add(i,r)}><Plus/></button></div>)}<div className="choice"><button className="primary" onClick={()=>addAll(r)}><ShoppingBasket/> Ajouter aux courses</button><button className="partner" onClick={deliver}><Truck/> Faire livrer</button></div><button className="cook"><Play/> Commencer à cuisiner</button></div></div></div>}
function Delivery({r,user,setUser,close,flash}:{r:Recipe;user:UserData;setUser:any;close:any;flash:any}){return <div className="overlay top"><div className="sheet delivery"><button className="back" onClick={close}><ChevronLeft/> Retour</button><div className="partnerLogo">allo<span>market</span></div><p className="eyebrow">PARTENAIRE DISTRIBUTEUR · SIMULATION</p><h1>Complète ton repas,<br/>sans détour.</h1><div className="address"><MapPin/><div><small>ADRESSE</small><input value={user.address} onChange={e=>setUser({...user,address:e.target.value})}/></div></div><div className="orderBox">{r.ingredients.map(i=><div key={i.name}><span>{i.name} <small>{i.qty}</small></span><b>{money(i.price)}</b></div>)}<hr/><div><span>Sous-total estimé</span><b>{money(r.price)}</b></div><div><span>Livraison</span><b>1 500 F</b></div><div className="total"><span>Total simulé</span><b>{money(r.price+1500)}</b></div></div><button className="cta" onClick={()=>flash("Simulation transmise à Allo Market")}>Commander <Truck/></button></div></div>}
function Shopping({user,setUser,flash}:{user:UserData;setUser:any;flash:any}){const done=user.cart.filter(x=>x.done).length,total=user.cart.length,pct=total?Math.round(done/total*100):0;const toggle=(id:string)=>{setUser((u:UserData)=>({...u,cart:u.cart.map(x=>x.id===id?{...x,done:!x.done}:x)}));flash("Progression enregistrée")};return <><div className="hello compact"><p>MISSION COURSES</p><h1>Plus proche du repas.</h1></div><div className="progressCard"><div><small>PROGRESSION</small><b>{pct}%</b></div><div className="bar"><i style={{width:pct+"%"}}/></div><p>{done}/{total} produits trouvés · <strong>3 850 F optimisés cette semaine</strong></p></div>{!total?<div className="empty"><ShoppingBasket/><h2>Ta liste est prête à se remplir.</h2><p>Choisis un repas. Eazy sépare ce que tu as déjà de ce qu’il reste réellement à acheter.</p></div>:<div className="list">{user.cart.map((x,n)=><button key={x.id} className={x.done?"done":""} onClick={()=>toggle(x.id)}><span className="check">{x.done?<Check/>:String(n+1).padStart(2,"0")}</span><div><b>{x.name}</b><small>{x.qty} · {x.recipe}</small></div><strong>{money(x.price)}</strong></button>)}</div>}<div className="mission"><Flame/><div><b>Objectif anti-gaspi</b><small>Termine ce panier en utilisant d’abord ce qui est déjà chez toi.</small></div></div></>}
function Profile({user,exportData,fileRef,importData}:{user:UserData;exportData:any;fileRef:any;importData:any}){return <><div className="profileHero"><div className="avatar large">{user.name[0]}</div><h1>{user.name}</h1><p>Ton espace cuisine personnel</p><div><b>11 450 F<small> optimisés</small></b><b>{user.streak}<small> jours de série</small></b></div></div><h2 className="subhead">Mes données</h2><div className="dataCard"><ScanLine/><div><b>Sauvegarde portable</b><p>Préférences, garde-manger et progression restent exportables en JSON.</p></div><button onClick={exportData}><Download/> Télécharger</button><button onClick={()=>fileRef.current?.click()}><Upload/> Importer</button><input ref={fileRef} hidden type="file" accept=".json,application/json" onChange={(e:any)=>importData(e.target.files?.[0])}/></div><div className="settings"><span><MapPin/> Adresse préférée <b>{user.address}</b></span><span><Truck/> Livraison <b>Allo Market</b></span></div></>}
